version: '3.8'
services:
  postgres:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
