version: '3.8'
services:
  postgres:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: password
    ports:
      - '${PG_PORT:-5432}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-dev@senomas.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - postgres-admin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"

volumes:
  postgres-data:
    driver: local
  postgres-admin:
    driver: local
